### ISSUE TITLE
idk how to solve this one

### ISSUE THREAD

**Issue by aurimassiaulys** [picklejason/ValorantRankedPointsBot#9]
2022-11-21 13:25:02 INFO     discord.client logging in using static token
2022-11-21 13:25:03 INFO     discord.gateway Shard ID None has connected to Gateway (Session ID: 45c6860b551ecf3f7bce953e95a8ca32).
Bot connected.
Traceback (most recent call last):
  File "/home/pi/valorantstats/ValorantRankedPointsBot/bot.py", line 111, in login
    player_id, headers = await val.run(username, password)
  File "/home/pi/valorantstats/ValorantRankedPointsBot/valorant_api.py", line 25, in run
    data = await r.json()
  File "/usr/local/lib/python3.9/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://auth.riotgames.com/api/v1/authorization')

**Comment by ConnorDoesDev** [comment]
Use an up-to-date User-Agent.
